global:
  domain: kullu.site
  repoUrl: git@github.com:edwinkullu/DevSecOps.git
  targetRevision: HEAD

projects:
  postpilot:
    description: "Main project for PostPilot microservices"
    sourceRepos:
      - "*"
    destinations:
      - server: https://kubernetes.default.svc
        namespace: postpilot
      - server: https://kubernetes.default.svc
        namespace: external-secrets
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:
  - name: external-secrets
    project: postpilot
    source:
      repoUrl: https://charts.external-secrets.io
      targetRevision: 0.9.13
      chart: external-secrets
    destination:
      server: https://kubernetes.default.svc
      namespace: external-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: postpilot-infra-prod
    project: postpilot
    source:
      path: deploy-as-code/helm/charts/postpilot-services/postpilot-infra
      targetRevision: HEAD
      helm:
        valueFiles:
          - ../../../environments/prod.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: postpilot
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: postpilot-gateway-prod
    project: postpilot
    source:
      path: deploy-as-code/helm/charts/postpilot-services/postpilot-gateway
      targetRevision: HEAD
      helm:
        valueFiles:
          - ../../../environments/prod.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: postpilot
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: dashboard-prod
    project: postpilot
    source:
      path: deploy-as-code/helm/charts/postpilot-services/dashboard
      targetRevision: HEAD
      helm:
        releaseName: dashboard
        valueFiles:
          - ../../../environments/prod.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: postpilot
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    imageUpdater:
      imageList: "dashboard=asia-docker.pkg.dev/postpilot-0/postpilot/dashboard"
      extraArgs:
        "dashboard.update-strategy": "latest"
        "dashboard.allow-tags": "regexp:^[0-9]{8}-[0-9]{6}$"

  - name: api-server-prod
    project: postpilot
    source:
      path: deploy-as-code/helm/charts/postpilot-services/api-server
      targetRevision: HEAD
      helm:
        releaseName: api-server
        valueFiles:
          - ../../../environments/prod.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: postpilot
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    imageUpdater:
      imageList: "api-server=asia-docker.pkg.dev/postpilot-0/postpilot/api-server"
      extraArgs:
        "api-server.update-strategy": "latest"
        "api-server.allow-tags": "regexp:^[0-9]{8}-[0-9]{6}$"

  - name: agent-engine-prod
    project: postpilot
    source:
      path: deploy-as-code/helm/charts/postpilot-services/agent-engine
      targetRevision: HEAD
      helm:
        releaseName: agent-engine
        valueFiles:
          - ../../../environments/prod.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: postpilot
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    imageUpdater:
      imageList: "agent-engine=asia-docker.pkg.dev/postpilot-0/postpilot/agent-engine"
      extraArgs:
        "agent-engine.update-strategy": "latest"
        "agent-engine.allow-tags": "regexp:^[0-9]{8}-[0-9]{6}$"
