# Global Configuration for Production
# Disable dynamic timestamp annotation to prevent unnecessary pod restarts
disableAnnotationTimestamp: true

global:
  environment: prod
  namespace: postpilot
  gsm:
    enabled: true
    location: "asia-south1"
    cluster_name: "postpilot-prod"
  gateway:
    enabled: true
    className: "gke-l7-global-external-managed"
    certMap: "postpilot-prod-cert-map"
    staticIpName: "postpilot-prod-ip"
    securityPolicyName: "postpilot-prod-security-policy"
    cdn:
      enabled: false
  pdb:
    enabled: false
  env_suffix: "prod"
  project_id: postpilot-0
  registry_base_url: asia-docker.pkg.dev/postpilot-0/postpilot
  domain: kullu.site
  memory_limits: "5Gi"

  host_urls:
    dashboard_url: "postpilot.kullu.site"
    api_url: "api-postpilot.kullu.site"
    agent_url: "agent-postpilot.kullu.site"
  env: |
    - name: NODE_ENV
      value: "production"

# --- SERVICE SPECIFIC OVERRIDES ---
services:
  dashboard:
    replicas: 2
    resources:
      cpu_requests: "200m"
      memory_requests: "512Mi"
      cpu_limits: "1000m"
      memory_limits: "1Gi"
  api-server:
    replicas: 2
    resources:
      cpu_requests: "200m"
      memory_requests: "512Mi"
      cpu_limits: "1000m"
      memory_limits: "1Gi"
  agent-engine:
    replicas: 2
    resources:
      cpu_requests: "200m"
      memory_requests: "1Gi"
      cpu_limits: "2000m"
      memory_limits: "2Gi"

