{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    {{- if .imageUpdater }}
    argocd-image-updater.argoproj.io/image-list: {{ .imageUpdater.imageList }}
    argocd-image-updater.argoproj.io/write-back-method: {{ .imageUpdater.writeBackMethod | default "argocd" }}
    {{- range $key, $val := .imageUpdater.extraArgs }}
    argocd-image-updater.argoproj.io/{{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoUrl | default $.Values.global.repoUrl }}
    targetRevision: {{ .source.targetRevision | default $.Values.global.targetRevision }}
    path: {{ .source.path }}
    {{- if .source.helm }}
    helm:
      valueFiles:
{{ toYaml .source.helm.valueFiles | indent 8 }}
    {{- end }}
  destination:
    server: {{ .destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .destination.namespace | default "postpilot" }}
  syncPolicy:
{{ toYaml .syncPolicy | indent 4 }}
---
{{- end }}
