environments:
  uat:
  prod:

---

repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io

templates:
  default: &default
    namespace: postpilot
    needs:
      - postpilot/external-secrets-config
    values:
      - environments/{{ if eq .Environment.Name "prod" }}prod{{ else }}stage{{ end }}.yaml

releases:
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    version: 0.9.13
    createNamespace: true
    wait: true
    # Automates the "Manual Lifecycle Control" you mentioned by handling readiness and cleanup.
    timeout: 600
    cleanupOnFail: true
    values:
      - installCRDs: true

  - name: external-secrets-config
    namespace: postpilot
    chart: charts/postpilot-services/postpilot-infra
    values:
      - environments/{{ if eq .Environment.Name "prod" }}prod{{ else }}stage{{ end }}.yaml
    needs:
      - external-secrets/external-secrets

  - name: postpilot-gateway
    <<: *default
    chart: charts/postpilot-services/postpilot-gateway

# Example application release:
#  - name: example-service
#    <<: *default
#    chart: charts/postpilot-services/example-service
