{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- $certMap := .Values.gateway.certMap | default .Values.global.gateway.certMap }}
    {{- if $certMap }}
    networking.gke.io/certmap: {{ $certMap | quote }}
    {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default .Values.global.gateway.className | default "gke-l7-global-external-managed" }}
  {{- $staticIpName := .Values.gateway.staticIpName | default .Values.global.gateway.staticIpName }}
  {{- if $staticIpName }}
  addresses:
    - type: NamedAddress
      value: {{ $staticIpName | quote }}
  {{- end }}
  listeners:
    {{- range .Values.gateway.listeners }}
    {{- if or (ne .protocol "HTTP") $.Values.gateway.allowHttp }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- end }}
{{- end }}
