# Default values for common.
# This chart is meant to be a library but provides defaults for safety.

global:
  environment: stage
  env_suffix: uat
  domain: kullu.site
  namespace: postpilot
  registry_base_url: me-central1-docker.pkg.dev/glassy-storm-491011-q6/postpilot-uat
  projectId: glassy-storm-491011-q6
  gateway:
    enabled: false
  gsm:
    enabled: true

replicas: 1
httpPort: 8080

image:
  repository: postpilot-service
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# Placeholder for optional features
ingress:
  enabled: false
  context: ""
  annotations: {}

affinity:
  preferSpreadAcrossAZ: false
